version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@here"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          mentions: "@here"
workflows:
  send-notification:
    jobs:
      - notify:
          context: Slack-build-noti
